### ISSUE TITLE
vcgencmd install

### ISSUE THREAD

**Issue by lucasfolino** [2bytes/website#28]
Your article was one of the only ones I was able to find on the installation of vcgencmd  on pi4 and Ubuntu 20.04.  After using your method I found out you can just install it using the package libraspberrypi-bin.  I didn't find any documentation on this any where in Ubuntu, but found it else ware.  I wanted to let you know since this seems to be supported and hidden and you won't have to go through a build of vcgencmd  for any of your pis.  Plus makes it easier to upgrade and automate.

If you want to install this package you have to remove libvchiq_arm.so, libvcos.so, and the vcgencmd.  The package will not overwrite these.

**Comment by hamid-elaosta** [comment]
@lucasfolino Thanks for contacting me to let me know. It looks like there are some other useful utils in there too!

```
$ dpkg --contents libraspberrypi-bin_0~20200520+git2fe4ca3-0ubuntu3~20.04_arm64.deb 
drwxr-xr-x root/root         0 2020-10-19 19:36 ./
drwxr-xr-x root/root         0 2020-10-19 19:36 ./usr/
drwxr-xr-x root/root         0 2020-10-19 19:36 ./usr/bin/
-rwxr-xr-x root/root     14264 2020-10-19 19:36 ./usr/bin/dtmerge
-rwxr-xr-x root/root     30736 2020-10-19 19:36 ./usr/bin/dtoverlay
-rwxr-xr-x root/root       282 2020-05-19 11:31 ./usr/bin/dtoverlay-post
-rwxr-xr-x root/root       280 2020-05-19 11:31 ./usr/bin/dtoverlay-pre
-rwxr-xr-x root/root     79320 2020-10-19 19:36 ./usr/bin/raspistill
-rwxr-xr-x root/root     88088 2020-10-19 19:36 ./usr/bin/raspivid
-rwxr-xr-x root/root     70760 2020-10-19 19:36 ./usr/bin/raspividyuv
-rwxr-xr-x root/root     66592 2020-10-19 19:36 ./usr/bin/raspiyuv
-rwxr-xr-x root/root     56048 2020-10-19 19:36 ./usr/bin/tvservice
-rwxr-xr-x root/root     18360 2020-10-19 19:36 ./usr/bin/vcgencmd
-rwxr-xr-x root/root     10168 2020-10-19 19:36 ./usr/bin/vcmailbox
...
```

**Comment by lucasfolino** [comment]
Also rpi-eeprom can be installed as well to update the eeprom.

**Comment by hamid-elaosta** [comment]
Thanks @lucasfolino I've added an update to the article and linked to this issue!
